# Base image with Python
FROM python:3.12-slim AS base

# Prevent Python from writing bytecode & buffering stdout
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    POETRY_VERSION=2.2.1 \
    POETRY_VIRTUALENVS_IN_PROJECT=true

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Install Poetry
ENV POETRY_VERSION=2.2.1
RUN curl -sSL https://install.python-poetry.org | python3 -

# Add Poetry to PATH
ENV PATH="/root/.local/bin:$PATH"

# Set workdir
WORKDIR /app

# Copy only dependency files to install before copying the project
COPY pyproject.toml poetry.lock README.md ./

# Install dependencies (including dev)
RUN poetry install --no-interaction --no-ansi --with dev --no-root

# Copy project files
COPY . .

# Expose Django dev server port
EXPOSE 8000

# Run Django development server
CMD ["poetry", "run", "python", "src/manage.py", "runserver", "0.0.0.0:8000"]
